name: Docker packaging

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - README.md

jobs:
  dockerBuild:
    name: Build & Push Docker Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read version
      run: |
        export VERTAG=`cat version.txt`
        echo "RELEASE_TAG=$VERTAG" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: mypochsm.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Container build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            zlatkoa/nginx-alsb:${{ env.RELEASE_TAG }}
            mypochsm.azurecr.io/nginx-alsb:${{ env.RELEASE_TAG }}
